project:
  type: book

book:
  title: "Mathematical Physics"
  author: "John Waczak"
  date: "9/13/2022"
  search: true
  chapters:
    - index.qmd
    - Manifolds.qmd
    - references.qmd

  page-footer: "Copyright 2022, John Waczak" 



format:
  html:
    theme: cosmo
    html-math-method: katex
    page-naviagion: true
  pdf:
    documentclass: scrbook
    

reference-location: margin
citation-location: margin



